import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#2f2f3d',
  },
  scrollView: {
    padding: 10,
  },
  chatItem: {
    marginTop: 30,
    borderRadius: 10,
    paddingHorizontal: 0,
    paddingVertical: 10,
    backgroundColor: '#414155',
    // shadowColor: '#fff',
    // shadowOffset: {
    //   width: 0,
    //   height: 2,
    // },
    // shadowOpacity: 0.25,
    // shadowRadius: 3.84,
    // elevation: 5,
    alignItems: 'center',
    // flex: 1,
    width: '100%',
  },
  inputContainer: {
    alignItems: 'center',
    backgroundColor: '#a3a3d5',
    padding: 10,
    borderTopWidth: 5,
    borderTopColor: '#f1f6ff',
    borderColor: '#f1f6ff',
    width: '100%',
  },
  input: {
    flex: 1,
    fontSize: 26,
    padding: 10,
    color: '#f1f6ff',
    backgroundColor: '#414155',
    borderRadius: 10,
    textAlignVertical: 'top',
    width: '95%',
  },
  sendButton: {
    flex: 1,
    width: '95%',
    backgroundColor: '#25bd9c',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginBottom: 5,
    alignItems: 'center',
  },
  sendButtonText: {
    fontSize: 26,
    color: '#eff3f6',
    fontWeight: 'bold',
  },
  chatRequest: {
    backgroundColor: '#353343',
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
    width: '95%',
    color: '#f1f6ff',
    fontSize: 26,
  },
  chatResponse: {
    backgroundColor: '#353343',
    borderRadius: 10,
    marginBottom: 10,
    padding: 10,
    width: '95%',
    color: '#f1f6ff',
    fontSize: 26,
  },
});
